name: receipt_scanner
description: A receipt scanner for your company

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_ml_vision:
  image_picker:
  image_cropper:
  path_provider: ^1.6.11
  mailer: ^3.0.4
  excel: ^1.1.5
  camera_camera: ^1.0.34+1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  provider: ^3.1.0
  flutter_spinkit: ^4.1.2+1
  http: ^0.12.0+3
  sqflite: ^1.3.1
  google_sign_in: ^4.5.1
  camera: ^0.5.8+5
  path: ^1.6.4
  auto_size_text: ^2.1.0
  flushbar: ^1.5.0
  rxdart: ^0.24.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/voucher_logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/image/google.png
  - assets/image/bg.png
  - assets/files/example.xlsx
  - assets/files/temp.xlsx
  - assets/background/top.png
  - assets/background/right.png
  - assets/background/bttm.png
  - assets/icon/google.png
  - assets/icon/facebook.png
  - assets/icon/apple.png
  - assets/icon/twitter.png
  - assets/icon/receipt_logo.png
  - assets/icon/splash_screen.png
  - assets/icon/profile.png
  - assets/icon/data.png
  - assets/icon/home.png
  - assets/icon/homeon.png
  - assets/icon/dataon.png
  - assets/icon/profileon.png
  - assets/icon/user.png
  - assets/icon/lock.png
  
  fonts:
    - family: xd
      fonts:
          - asset: fonts/bg.ttf
            weight: 600
    - family: Spartan
      fonts:
          - asset: fonts/Spartan-VariableFont_wght.ttf

    - family: Spartan-Black
      fonts:
          - asset: fonts/Spartan-Black.ttf

    - family: Spartan-Bold
      fonts:
          - asset: fonts/Spartan-Bold.ttf

    - family: Spartan-ExtraBold
      fonts:
          - asset: fonts/Spartan-ExtraBold.ttf

    - family: Spartan-ExtraLight
      fonts:
          - asset: fonts/Spartan-ExtraLight.ttf

    - family: Spartan-Light
      fonts:
          - asset: fonts/Spartan-Light.ttf

    - family: Spartan-Medium
      fonts:
          - asset: fonts/Spartan-Medium.ttf

    - family: Spartan-Regular
      fonts:
          - asset: fonts/Spartan-Regular.ttf

    - family: Spartan-SemiBold
      fonts:
          - asset: fonts/Spartan-SemiBold.ttf

    - family: Spartan-Thin
      fonts:
          - asset: fonts/Spartan-Thin.ttf

    - family: FredokaOne
      fonts:
          - asset: fonts/FredokaOne-Regular.ttf

    - family: Righteous-Regular
      fonts:
          - asset: fonts/Righteous-Regular.ttf

    - family: ConcertOne
      fonts:
          - asset: fonts/ConcertOne-Regular.ttf

    - family: OpenSansRegular
      fonts:
          - asset: fonts/OpenSans-Regular.ttf

    - family: OpenSansBold
      fonts:
          - asset: fonts/OpenSans-Bold.ttf

    - family: Cookie
      fonts:
          - asset: fonts/Cookie-Regular.ttf

    - family: Courgette
      fonts:
          - asset: fonts/Courgette-Regular.ttf

    - family: Raleway-Regular
      fonts:
          - asset: fonts/Raleway-Regular.ttf

    - family: Raleway-ExtraBold
      fonts:
          - asset: fonts/Raleway-ExtraBold.ttf

    - family: Raleway-Bold
      fonts:
          - asset: fonts/Raleway-Bold.ttf

    - family: Raleway-Black
      fonts:
          - asset: fonts/Raleway-Black.ttf   

    - family: Lobster
      fonts:
          - asset: fonts/Lobster-Regular.ttf 
